credentials:
  usernames:
    admin:
      name: Admin
      email: admin@gmail.com
      password: abc

cookie:
  expiry_days: 30
  key: qwerty
  name: random_cookie_name

preauthorized:
  emails:
    -admin@gmail.com